// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using STA.Core.Data;

#nullable disable

namespace STA.Worker.Data.Migrations
{
    [DbContext(typeof(StaDbContext))]
    [Migration("20260714212017_AddEtapasRotasLogArquivo")]
    partial class AddEtapasRotasLogArquivo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sta")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("STA.Core.Data.Entities.EtapaTransferencia", b =>
                {
                    b.Property<int>("CnEtapa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cn_etapa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CnEtapa"));

                    b.Property<int>("CnSistema")
                        .HasColumnType("integer")
                        .HasColumnName("cn_sistema");

                    b.Property<DateTime?>("DtAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_alteracao");

                    b.Property<DateTime>("DtCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_criacao")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("FlAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("fl_ativo");

                    b.Property<string>("HrFimJanela")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("hr_fim_janela");

                    b.Property<string>("HrInicioJanela")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("hr_inicio_janela");

                    b.Property<string>("NmEtapa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nm_etapa");

                    b.Property<int?>("NrIntervaloMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("nr_intervalo_minutos");

                    b.Property<int>("NrOrdemExecucao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("nr_ordem_execucao");

                    b.HasKey("CnEtapa");

                    b.HasIndex("CnSistema", "FlAtivo");

                    b.ToTable("tbl_etapa_transferencia", "sta");
                });

            modelBuilder.Entity("STA.Core.Data.Entities.LogArquivo", b =>
                {
                    b.Property<long>("CnLogArquivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("cn_log_arquivo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CnLogArquivo"));

                    b.Property<int?>("CnEtapa")
                        .HasColumnType("integer")
                        .HasColumnName("cn_etapa");

                    b.Property<int?>("CnLogProcesso")
                        .HasColumnType("integer")
                        .HasColumnName("cn_log_processo");

                    b.Property<int?>("CnRota")
                        .HasColumnType("integer")
                        .HasColumnName("cn_rota");

                    b.Property<string>("DsDiretorioDestino")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ds_diretorio_destino");

                    b.Property<string>("DsDiretorioOrigem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ds_diretorio_origem");

                    b.Property<string>("DsMensagem")
                        .HasColumnType("text")
                        .HasColumnName("ds_mensagem");

                    b.Property<DateTime?>("DtFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_fim");

                    b.Property<DateTime>("DtInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_inicio");

                    b.Property<bool>("FlCompactado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("fl_compactado");

                    b.Property<bool>("FlDescompactado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("fl_descompactado");

                    b.Property<string>("IdStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("id_status");

                    b.Property<string>("NmArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nm_arquivo");

                    b.Property<long>("NrTamanhoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("nr_tamanho_bytes");

                    b.HasKey("CnLogArquivo");

                    b.HasIndex("CnLogProcesso");

                    b.HasIndex("CnRota");

                    b.HasIndex("NmArquivo");

                    b.HasIndex("CnEtapa", "DtInicio");

                    b.HasIndex("IdStatus", "DtInicio");

                    b.ToTable("tbl_log_arquivo", "sta");
                });

            modelBuilder.Entity("STA.Core.Data.Entities.LogProcesso", b =>
                {
                    b.Property<int>("CnLogProcesso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cn_log_processo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CnLogProcesso"));

                    b.Property<int>("CnProcesso")
                        .HasColumnType("integer")
                        .HasColumnName("cn_processo");

                    b.Property<int>("CnSistema")
                        .HasColumnType("integer")
                        .HasColumnName("cn_sistema");

                    b.Property<DateTime?>("DtFimProcesso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_fim_processo");

                    b.Property<DateTime>("DtInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_inicio")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("IdStatusProcesso")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("id_status_processo");

                    b.Property<long>("QtRegistrosErro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("qt_registros_erro");

                    b.Property<long>("QtRegistrosProcessados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("qt_registros_processados");

                    b.Property<long>("VlRegistrosErro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("vl_registros_erro");

                    b.Property<long>("VlRegistrosProcessados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("vl_registros_processados");

                    b.Property<string>("XmlObsProcesso")
                        .HasColumnType("text")
                        .HasColumnName("xml_obs_processo");

                    b.HasKey("CnLogProcesso");

                    b.HasIndex("DtInicio");

                    b.HasIndex("CnSistema", "CnProcesso");

                    b.ToTable("tbl_log_processo", "sta");
                });

            modelBuilder.Entity("STA.Core.Data.Entities.ParametroSistema", b =>
                {
                    b.Property<int>("CnParametroSistema")
                        .HasColumnType("integer")
                        .HasColumnName("cn_parametro_sistema");

                    b.Property<int>("CnSistema")
                        .HasColumnType("integer")
                        .HasColumnName("cn_sistema");

                    b.Property<string>("CdParametroSistema")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cd_parametro_sistema");

                    b.HasKey("CnParametroSistema", "CnSistema");

                    b.HasIndex("CnSistema");

                    b.ToTable("tbl_parametro_sistema", "sta");
                });

            modelBuilder.Entity("STA.Core.Data.Entities.RotaDestino", b =>
                {
                    b.Property<int>("CnRotaDestino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cn_rota_destino");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CnRotaDestino"));

                    b.Property<int>("CnRota")
                        .HasColumnType("integer")
                        .HasColumnName("cn_rota");

                    b.Property<string>("DsDescompactaDestino")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ds_descompacta_destino");

                    b.Property<string>("DsDiretorioDestino")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ds_diretorio_destino");

                    b.Property<bool>("FlAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("fl_ativo");

                    b.Property<int>("NrOrdem")
                        .HasColumnType("integer")
                        .HasColumnName("nr_ordem");

                    b.HasKey("CnRotaDestino");

                    b.HasIndex("CnRota");

                    b.ToTable("tbl_rota_destino", "sta");
                });

            modelBuilder.Entity("STA.Core.Data.Entities.RotaTransferencia", b =>
                {
                    b.Property<int>("CnRota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cn_rota");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CnRota"));

                    b.Property<int>("CnEtapa")
                        .HasColumnType("integer")
                        .HasColumnName("cn_etapa");

                    b.Property<string>("DsCompactaOrigemTipo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ds_compacta_origem_tipo");

                    b.Property<string>("DsDiretorioBackup")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ds_diretorio_backup");

                    b.Property<string>("DsDiretorioOrigem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ds_diretorio_origem");

                    b.Property<string>("DsMascaraArquivo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("*")
                        .HasColumnName("ds_mascara_arquivo");

                    b.Property<bool>("FlAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("fl_ativo");

                    b.Property<bool>("FlExcluirOrigem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("fl_excluir_origem");

                    b.Property<int>("NrDiasExcluir")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("nr_dias_excluir");

                    b.Property<int>("NrOrdem")
                        .HasColumnType("integer")
                        .HasColumnName("nr_ordem");

                    b.Property<long>("NrTamanhoFinalBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("nr_tamanho_final_bytes");

                    b.Property<long>("NrTamanhoInicialBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("nr_tamanho_inicial_bytes");

                    b.HasKey("CnRota");

                    b.HasIndex("CnEtapa", "NrOrdem");

                    b.ToTable("tbl_rota_transferencia", "sta");
                });

            modelBuilder.Entity("STA.Core.Data.Entities.Sistema", b =>
                {
                    b.Property<int>("CnSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cn_sistema");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CnSistema"));

                    b.Property<string>("CdAliasSistema")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cd_alias_sistema");

                    b.HasKey("CnSistema");

                    b.HasIndex("CdAliasSistema")
                        .IsUnique();

                    b.ToTable("tbl_sistema", "sta");
                });

            modelBuilder.Entity("STA.Core.Data.Entities.EtapaTransferencia", b =>
                {
                    b.HasOne("STA.Core.Data.Entities.Sistema", "Sistema")
                        .WithMany()
                        .HasForeignKey("CnSistema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("STA.Core.Data.Entities.LogArquivo", b =>
                {
                    b.HasOne("STA.Core.Data.Entities.EtapaTransferencia", "Etapa")
                        .WithMany()
                        .HasForeignKey("CnEtapa")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("STA.Core.Data.Entities.LogProcesso", "LogProcesso")
                        .WithMany()
                        .HasForeignKey("CnLogProcesso")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("STA.Core.Data.Entities.RotaTransferencia", "Rota")
                        .WithMany()
                        .HasForeignKey("CnRota")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Etapa");

                    b.Navigation("LogProcesso");

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("STA.Core.Data.Entities.LogProcesso", b =>
                {
                    b.HasOne("STA.Core.Data.Entities.Sistema", "Sistema")
                        .WithMany("Logs")
                        .HasForeignKey("CnSistema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("STA.Core.Data.Entities.ParametroSistema", b =>
                {
                    b.HasOne("STA.Core.Data.Entities.Sistema", "Sistema")
                        .WithMany("Parametros")
                        .HasForeignKey("CnSistema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("STA.Core.Data.Entities.RotaDestino", b =>
                {
                    b.HasOne("STA.Core.Data.Entities.RotaTransferencia", "Rota")
                        .WithMany("Destinos")
                        .HasForeignKey("CnRota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("STA.Core.Data.Entities.RotaTransferencia", b =>
                {
                    b.HasOne("STA.Core.Data.Entities.EtapaTransferencia", "Etapa")
                        .WithMany("Rotas")
                        .HasForeignKey("CnEtapa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etapa");
                });

            modelBuilder.Entity("STA.Core.Data.Entities.EtapaTransferencia", b =>
                {
                    b.Navigation("Rotas");
                });

            modelBuilder.Entity("STA.Core.Data.Entities.RotaTransferencia", b =>
                {
                    b.Navigation("Destinos");
                });

            modelBuilder.Entity("STA.Core.Data.Entities.Sistema", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Parametros");
                });
#pragma warning restore 612, 618
        }
    }
}
